# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: brocode

before:
  hooks:
    - go mod tidy

builds:
  - id: brocode
    main: ./cmd/brocode
    binary: brocode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/plumpslabs/bro-code/internal/version.Version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format: tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: plumpslabs
    name: bro-code
  mode: replace
  replace_existing_artifacts: true
  replace_existing_draft: true
  draft: false
  prerelease: auto
